name: my_project
description: A simple Dart project
version: 1.0.0
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  # Add external packages here
  http: ^1.1.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
